# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'FCObjectCase' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'FCCollectionViewLayout'
  
  pod 'Masonry'
  pod 'CTMediator'
  pod 'FCBaseKit', :git => 'https://github.com/Q007shi/FCBaseKit.git'
  pod 'FCCategoryOCKit', :git => 'https://github.com/Q007shi/FCCategoryOCKit.git'

end
